version: 0.2
phases:
  install:
    commands:
      - yum update -y
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo AWS_ACCOUNT_ID $AWS_ACCOUNT_ID
      - echo AWS_DEFAULT_REGION $AWS_DEFAULT_REGION
      - echo IMAGE_REPO_NAME $IMAGE_REPO_NAME
      - echo IMAGE_TAG $IMAGE_TAG
      - (aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 568276182587.dkr.ecr.eu-west-1.amazonaws.com)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd $SRC_DIR
      - docker build -t anyupp-codebuild .
      - docker tag anyupp-codebuild:latest 568276182587.dkr.ecr.eu-west-1.amazonaws.com/anyupp-codebuild:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 568276182587.dkr.ecr.eu-west-1.amazonaws.com/anyupp-codebuild:latest
